## ECON 833 PS 2
## Ningqiao Li

### Standard Library Chapter Q1

In [40]:
import numpy as np

def my_func (L):
    min_L = min(L)
    max_L = max(L)
    avg_L = np.mean(L) 
    print("min value", min_L)
    print("max value", max_L)
    print("mean value", avg_L)

In [41]:
L = [1, 2, 3, 4]

In [42]:
my_func(L)

min value 1
max value 4
mean value 2.5


### Standard Library Chapter Q2

In [17]:
# For int
int1 = 100
int2 = int1
int2 = 50
int1 == int2

False

In [35]:
# For str
str1 = "Ningqiao"
str2 = str1
str2 = "Rui"
print(str1 == str2)
str2

False


'Rui'

In [31]:
# For list
list1 = [1, 2, 3, 'a']
list2 = list1
list2[1] = 'b'
list1 == list2
list2

[1, 'b', 3, 'a']

In [30]:
# for tuple
tuple1 = (1, 2, 3, 'a')
tuple2 = tuple1
# tuple2 = tuple2 +(1,)
tuple2 += (1,)
tuple1 == tuple2
tuple2


(1, 2, 3, 'a', 1)

In [39]:
# for set
set1 = {1, 2, 3, 'a'}
set2 = set1
set2 = {'b'}
set1 == set2

False

### Standard Library Chapter Q3

In [17]:
# please see the calculator.py for the specific function
import calculator as cal

In [18]:
cal.my_func(3, 4)

5.0

### Intro to Numpy Q1

In [25]:
import numpy as np
A = np.array([[3, -1, 4], [1, 5, -9]])
A

array([[ 3, -1,  4],
       [ 1,  5, -9]])

In [24]:
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
B

array([[ 2,  6, -5,  3],
       [ 5, -8,  9,  7],
       [ 9, -3, -2, -3]])

In [27]:
AB = np.dot(A, B)
AB

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [28]:
AB = A @ B
AB

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

### Intro to Numpy Q2

In [29]:
A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
A

array([[ 3,  1,  4],
       [ 1,  5,  9],
       [-5,  3,  1]])

In [35]:
result = - (A @ A @ A) + 9 * (A @ A) - 15 * A
result

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Intro to Numpy Q5

In [46]:
A = np.array([[0, 2, 4], [1, 3, 5]])
A

array([[0, 2, 4],
       [1, 3, 5]])

In [47]:
B = np.array([[3, 0, 0], [3, 3, 0], [3, 3, 3]])
B

array([[3, 0, 0],
       [3, 3, 0],
       [3, 3, 3]])

In [48]:
C = np.diag([-2, -2, -2])
C

array([[-2,  0,  0],
       [ 0, -2,  0],
       [ 0,  0, -2]])

In [49]:
A.T

array([[0, 1],
       [2, 3],
       [4, 5]])

In [51]:
col_1 = np.vstack((np.zeros((3, 3)), A, B))
col_1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 2., 4.],
       [1., 3., 5.],
       [3., 0., 0.],
       [3., 3., 0.],
       [3., 3., 3.]])

In [52]:
col_2 = np.vstack((A.T, np.zeros((5, 2))))
col_2

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
col_3 = np.vstack((np.eye(3), np.zeros((2, 3)), C))
col_3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [-2.,  0.,  0.],
       [ 0., -2.,  0.],
       [ 0.,  0., -2.]])

In [60]:
result = np. hstack((col_1, col_2, col_3))
result

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

### Object Oriented Q1

In [65]:
class Backpack:
    """
    Backpack class 
    """
    def __init__(self, name, color, max_size=5):
        self.name = name
        self.max_size = max_size
        self.color = color
        self.contents = []
        
    def put(self, item):
        """Add 'item' to the backpack's list of contents. """
        if len(self.contents) >= self.max_size:
            print("No Room!")
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        
        self.contents.remove(item)
        
    def dump(self):
        "empty contents in the backpack"
        self.contents = []
        print("backpack has been dumped")
        


def test_backpack():
    testpack = Backpack("Barry", "black", 5)       # Instantiate the object.
    if testpack.name != "Barry":                # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer", "hahaha", "lol"]:
        testpack.put(item)                      # Test a method.
    print("Contents:", testpack.contents)   

test_backpack()

No Room!
Contents: ['pencil', 'pen', 'paper', 'computer', 'hahaha']


### Object Oriented Q2

In [71]:
class Jetpack(Backpack):
    def __init__(self, name, color, max_size = 2):
        Backpack.__init__(self, name, color, max_size)
        self.fuel = 10  
        """Override and store the fuel as an attribute."""
    
    def fly(self, burned_amount): #define the fly() method.
        self.remain = self.fuel - self.burned_amount
        if self.remain > self.burned_amount:
            print("Not enough fuel!")
        else:
            self.fuel = self.fuel - self.burned_amount
        """An amount of fuel to be burned and decrements the fuel attribute by that amount."""
    
    def dump(self):
        "empty contents and fuel tank in the backpack"
        self.contents = []
        self.fuel = 0
        print("backpack and fuel tank has been dumped")